# Make sure to check the documentation at https://goreleaser.com
project_name: osportpatch
universal_binaries:
  - replace: true
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
builds:
  - binary: osportpatch
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
archives:
  - files:
      - LICENSE.md
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
#checksum:
#  name_template: 'checksums.txt'
release:
  prerelease: "true"
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  skip: true

